name: Angular CI/CD

on:
  push:
    branches:
      - main # Cambia 'main' por el nombre de tu rama principal

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.18.0' # Puedes cambiar la versión según tus necesidades

    - name: Install dependencies
      run: npm install
      # working-directory: ./renta_raiz_frontend-2 # Cambia esto al directorio de tu aplicación Angular

    - name: Build Angular app
      run: npm run build --prod
      # working-directory: ./renta_raiz_frontend-2 # Cambia esto al directorio de tu aplicación Angular

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        
        docker build -t duhudico/renta_raiz_frontend-2 .
        docker push duhudico/renta_raiz_frontend_2
      env:
        DOCKER_BUILDKIT: 1

    - name: Trigger container update
      run: |
        curl -X POST http://157.173.210.108:8090/v1/update \
          -H "Authorization: Bearer tatin1421"
